# Generated by Django 4.2.1 on 2025-01-19 11:59

from django.db import migrations, models
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('telegram_id', models.BigIntegerField(db_index=True, default=None, null=True, unique=True, verbose_name='Телеграм ID')),
                ('username', models.CharField(db_index=True, default=None, max_length=70, null=True, unique=True, verbose_name='Имя пользователя')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='Номер телефона')),
                ('bot_start_link', models.CharField(editable=False, max_length=150, unique=True, verbose_name='Ссылка для запуска бота')),
                ('bot_link_status', models.CharField(choices=[('NOT_ACTIVATED', 'Не активирована'), ('ACTIVATED', 'Активирована')], default='NOT_ACTIVATED', max_length=50, verbose_name='Статус ссылки')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Telegram пользователи',
            },
        ),
    ]
