# Generated by Django 4.2.1 on 2025-01-19 11:59

from django.db import migrations, models
import web.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.CharField(db_index=True, default=web.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка на группу')),
                ('members', models.ManyToManyField(to='telegram_users.telegramuser', verbose_name='Учасники')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
